# Generated by Django 4.1 on 2023-06-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.JSONField(),
        ),
    ]
