# Generated by Django 4.1 on 2023-06-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0002_alter_project_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('tags', models.CharField(max_length=200)),
                ('draft', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
