# Generated by Django 4.1 on 2023-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0004_alter_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
